site_name: Text-to-Speech with TensorFlowTTS
site_url: https://w11wo.github.io/TensorFlowTTS/
repo_url: https://github.com/w11wo/TensorFlowTTS
docs_dir: docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    # - navigation.expand
    - content.code.annotate

plugins:
  - search
  - glightbox

markdown_extensions:
  # enable image captions
  - attr_list
  - md_in_html
  # admonitions
  - admonition
  # python support
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # task list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Home: index.md
  - Installation: guides/installation.md
  - Audio Samples: audio.md
  - Live Demo: https://huggingface.co/spaces/bookbot/Text-to-Speech-Playground
  - Model Zoo:
      - English: models/english.md
      - Indonesian: models/indonesian.md
  - Guides:
      - Train LightSpeech & Multi-band MelGAN:
          - Introduction: guides/lightspeech-mbmelgan/intro.md
          - Dataset: guides/lightspeech-mbmelgan/dataset.md
          - Duration Extraction: guides/lightspeech-mbmelgan/duration-extraction.md
          - Training: guides/lightspeech-mbmelgan/training.md
          - Inference: guides/lightspeech-mbmelgan/inference.md
      - Convert and Infer Models on TensorFlowLite: guides/tensorflowlite.md
